// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $NuevoContacto from "./routes/NuevoContacto.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $ChatMensajes from "./islands/ChatMensajes.tsx";
import * as $ListaContactos from "./islands/ListaContactos.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/NuevoContacto.tsx": $NuevoContacto,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/ChatMensajes.tsx": $ChatMensajes,
    "./islands/ListaContactos.tsx": $ListaContactos,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
